### ISSUE TITLE
[rosetta cUSD] re-run all cUSD reconciliation checks

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/rosetta-cusd#6]
It's been 4-5 months since running the full checks -- preemptively re-run everything and iron our any issues that have come up in the meantime
- [x] full CLI checks on alfajores
- [x] "" on mainnet
- [x] double check that README instructions for setup make sense and work as expected
- [x] double check no issues around donut

(Time estimate: running the full checks themselves will take several days, but the work around setting up, checking, debugging should be <1 day)

**Comment by barbaraliau** [comment]
Need to leave machine up and running this whole time

**Comment by barbaraliau** [comment]
Core Rosetta module: >= 8GB RAM, +45GB Alfajores, +100GB Mainnet

**Comment by eelanagaraj** [comment]
note: can stop/start checks by adding a path to the `cli-config` for the `data_directory` -- this will then save checks up until the point that they are killed and can be restarted at a later time from this point.

**Comment by eelanagaraj** [comment]
Currently running mainnet tests (started: Tues 18 May evening, around 6pm) from the branch `eelanagaraj/blockchain-upgrades`

This branch should also be used for alfajores tests, as they include the bump from `1.3.0` -> `1.3.2` and update to the tip of `beta/construction` as well, and a small fix to the README which should help with building/setup of the cUSD module.

**Comment by eelanagaraj** [comment]
Mainnet: no reconciliation errors

### Mainnet results

Success: Reconciliation Coverage End Condition [Coverage: 96.779092%]

+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation         | PASSED |
|                    | serviced all requests          |        |
+--------------------+--------------------------------+--------+
| Response Assertion | All responses are correctly    | PASSED |
|                    | formatted                      |        |
+--------------------+--------------------------------+--------+
| Block Syncing      | Blocks are connected into a    | PASSED |
|                    | single canonical chain         |        |
+--------------------+--------------------------------+--------+
| Balance Tracking   | Account balances did not go    | PASSED |
|                    | negative                       |        |
+--------------------+--------------------------------+--------+
| Reconciliation     | No balance discrepencies were  | PASSED |
|                    | found between computed and     |        |
|                    | live balances                  |        |
+--------------------+--------------------------------+--------+

+--------------------------+--------------------------------+-------------+
|     CHECK:DATA STATS     |          DESCRIPTION           |    VALUE    |
+--------------------------+--------------------------------+-------------+
| Blocks                   | # of blocks synced             |     6816973 |
+--------------------------+--------------------------------+-------------+
| Orphans                  | # of blocks orphaned           |           0 |
+--------------------------+--------------------------------+-------------+
| Transactions             | # of transaction processed     |     2768236 |
+--------------------------+--------------------------------+-------------+
| Operations               | # of operations processed      |    10392090 |
+--------------------------+--------------------------------+-------------+
| Accounts                 | # of accounts seen             |      447824 |
+--------------------------+--------------------------------+-------------+
| Active Reconciliations   | # of reconciliations performed |     6530498 |
|                          | after seeing an account in a   |             |
|                          | block                          |             |
+--------------------------+--------------------------------+-------------+
| Inactive Reconciliations | # of reconciliations performed |    45258120 |
|                          | on randomly selected accounts  |             |
+--------------------------+--------------------------------+-------------+
| Exempt Reconciliations   | # of reconciliation failures   |           0 |
|                          | considered exempt              |             |
+--------------------------+--------------------------------+-------------+
| Failed Reconciliations   | # of reconciliation failures   |           0 |
+--------------------------+--------------------------------+-------------+
| Skipped Reconciliations  | # of reconciliations skipped   |           0 |
+--------------------------+--------------------------------+-------------+
| Reconciliation Coverage  | % of accounts that have been   | 100.000000% |
|                          | reconciled                     |             |
+--------------------------+--------------------------------+-------------+

**Comment by eelanagaraj** [comment]
### alfajores results

+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation         | PASSED |
|                    | serviced all requests          |        |
+--------------------+--------------------------------+--------+
| Response Assertion | All responses are correctly    | PASSED |
|                    | formatted                      |        |
+--------------------+--------------------------------+--------+
| Block Syncing      | Blocks are connected into a    | PASSED |
|                    | single canonical chain         |        |
+--------------------+--------------------------------+--------+
| Balance Tracking   | Account balances did not go    | PASSED |
|                    | negative                       |        |
+--------------------+--------------------------------+--------+
| Reconciliation     | No balance discrepencies were  | PASSED |
|                    | found between computed and     |        |
|                    | live balances                  |        |
+--------------------+--------------------------------+--------+

+--------------------------+--------------------------------+-------------+
|     CHECK:DATA STATS     |          DESCRIPTION           |    VALUE    |
+--------------------------+--------------------------------+-------------+
| Blocks                   | # of blocks synced             |     5276120 |
+--------------------------+--------------------------------+-------------+
| Orphans                  | # of blocks orphaned           |           0 |
+--------------------------+--------------------------------+-------------+
| Transactions             | # of transaction processed     |      129517 |
+--------------------------+--------------------------------+-------------+
| Operations               | # of operations processed      |      438419 |
+--------------------------+--------------------------------+-------------+
| Accounts                 | # of accounts seen             |       16170 |
+--------------------------+--------------------------------+-------------+
| Active Reconciliations   | # of reconciliations performed |      314117 |
|                          | after seeing an account in a   |             |
|                          | block                          |             |
+--------------------------+--------------------------------+-------------+
| Inactive Reconciliations | # of reconciliations performed |    20819659 |
|                          | on randomly selected accounts  |             |
+--------------------------+--------------------------------+-------------+
| Exempt Reconciliations   | # of reconciliation failures   |           0 |
|                          | considered exempt              |             |
+--------------------------+--------------------------------+-------------+
| Failed Reconciliations   | # of reconciliation failures   |           0 |
+--------------------------+--------------------------------+-------------+
| Skipped Reconciliations  | # of reconciliations skipped   |           0 |
+--------------------------+--------------------------------+-------------+
| Reconciliation Coverage  | % of accounts that have been   | 100.000000% |
|                          | reconciled                     |             |
+--------------------------+--------------------------------+-------------+

**Comment by medhakothari** [comment]
Confirmed that README instructions for setup make sense and work as expected

Also ran the tests a few days ago too, just for fun and they had no reconciliation errors!
